#! /usr/bin/env python3

from sys import argv, exit
from PyQt5.QtWidgets import QApplication
from orchid import DesktopEnvironment

if __name__ == '__main__':
    # Create the Qt app.
    app = QApplication(argv)
    app.setApplicationName("Orchid")
    app.setApplicationVersion("2019.7.18")
    # TODO: app.setWindowIcon()

    # Create the desktop environment.
    de = DesktopEnvironment()
    de.run()

    # Run the app and return the exit code.
    exit_code = app.exec()
    exit(exit_code)
